#######################################################################################
#######################################################################################
#######################################################################################
#####                                                                             #####
#####                             dCeggs 1.0                                      #####
#####                         Created By Driftay                                  #####
#####                                                                             #####
#######################################################################################
#######################################################################################
#######################################################################################

#<-------------------------------------->NOTES<-------------------------------------->#
#All Color Codes Can Be Used!
#Refer to: https://wiki.ess3.net/mc/
#<-------------------------------------->NOTES<-------------------------------------->#

Throwable:
  Item:
    Glow: true
    Name: '&2&lThrowable Creeper &7(Right Click)'
    Lore:
      - '&f&lInformation'
      - '&7(Right Click to Throw)'
      - ' '
      - '- &7Explosion Time: &f2 Seconds'

  Creeper-Manager:
    Explode-Radius: 3
    Explode-Timer: 2.0