#######################################################################################
#######################################################################################
#######################################################################################
#####                                                                             #####
#####                        SaberExplosives 1.0                                  #####
#####                         Created By Driftay                                  #####
#####                                                                             #####
#######################################################################################
#######################################################################################
#######################################################################################

#<-------------------------------------->NOTES<-------------------------------------->#
#All Color Codes Can Be Used!
#Refer to: https://wiki.ess3.net/mc/
#<-------------------------------------->NOTES<-------------------------------------->#

Use-Throwable-Creeper-Eggs: true
Use-Semtex: true


Throwable:
  CreeperEgg:
    Item:
      Glow: true
      Name: '&2&lThrowableCreeper &7(Right Click)'
      Lore:
        - '&f&lInformation'
        - '&7(Right Click to Throw)'
        - ' '
        - '- &7Explosion Time: &f2 Seconds'
  SnowBall:
    Item:
      Glow: true
      Name: '&c&lSemtex &7(Right Click)'
      Lore:
        - '&f&lInformation'
        - '&7(Right Click to Throw)'
        - ' '
        - '- &7Explosion Time: &fInstant on impact'

  Creeper-Manager:
    Explode-Radius: 3 #Applies to Both Functions
    Explode-Timer: 2.0 #CreeperEggs Only