name: SaberExplosives
main: me.driftay.explosive.SaberExplosives
version: ${project.version}
author: Driftay
description: The Ultimate Creeper Egg Throwing Plugin
commands:
  scegg:
    description: Give Throwable Creeper Eggs
  semtex:
    description: Give Semtex's
permissions:
  saberexplosives.give:
    description: Grants Ability to give Throwable Creeper Eggs & Semtex's